app:
  host: 0.0.0.0
  port: 1984
  workers: 4
  reload: true
  origins: http://0.0.0.0:8080, http://localhost:8080, http://localhost
databases:
  mongo_url: mongodb://smart_design_user:123456@0.0.0.0:27017/smart_design_mongo

